# Generated by Django 5.1.1 on 2024-09-20 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_boot_processes', 'Can boot processes'), ('can_restart_processes', 'Can restart processes'), ('can_flush_processes', 'Can flush processes'), ('can_kill_processes', 'Can kill processes'), ('can_view_process_logs', 'Can view process logs')]},
        ),
    ]
